### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by LeonardKoll** [KitesForFuture/kite#23]
![Screenshot_20210308-121408_Telegram](https://user-images.githubusercontent.com/20996097/110314234-e0d34280-8007-11eb-8dba-cf71e4d2f206.jpg)
![Screenshot_20210308-121341_Telegram](https://user-images.githubusercontent.com/20996097/110314236-e2046f80-8007-11eb-9a08-13e900dd6d12.jpg)

**Comment by kite-chan** [comment]
Die outliers konnten offenbar auch weiter als 20x entfernt liegen. habe sie entsprechend erkannt und rausgeschmissen.
